In [1]:
import numpy as np

In [3]:
a=np.array([[1,2,3,4,5],
           [1,2,3,4,5]],dtype=int)

In [4]:
print(a)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [5]:
a

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [7]:
a.shape

(2, 5)

In [8]:
print(type(a))

<class 'numpy.ndarray'>


In [9]:
print(len(a))

2


In [10]:
print(a.ndim)

2


In [11]:
a1=a.reshape(10,1)

In [13]:
print(a1)

[[1]
 [2]
 [3]
 [4]
 [5]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [14]:
a2=a.reshape(1,10)

In [15]:
print(a2)

[[1 2 3 4 5 1 2 3 4 5]]


In [16]:
a3=a.reshape(1,-1)

In [17]:
list_1=[1,2,3,4,5]
list_2=[2,3,4,5,6]
list_3=[9,7,6,8,9]
mul_l=np.array([list_1,list_2,list_3],dtype=int)

In [18]:
mul_l

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [20]:
print(mul_l.shape)

(3, 5)


In [21]:
mul_l=mul_l.reshape(1,15)

In [22]:
print(mul_l.shape)

(1, 15)


In [23]:
print(mul_l)

[[1 2 3 4 5 2 3 4 5 6 9 7 6 8 9]]


In [24]:
mul_l.shape=(3,5)
print(mul_l)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [26]:
import numpy as np

In [27]:
a1=np.array(24)
print(a1)

24


In [28]:
type(a1)

numpy.ndarray

In [29]:
print(a1.ndim)

0


In [30]:
a1.shape

()

In [32]:
b=a1.reshape(2,6,2)
print(b)

ValueError: cannot reshape array of size 1 into shape (2,6,2)

In [33]:
#byte size
# 1 byte=8 bits
x=np.array([1,2,3,4,5],dtype=np.int8)
print(x.itemsize)

1


In [35]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [36]:
x

array([[1., 2.],
       [3., 4.]])

In [37]:
y

array([[5., 6.],
       [7., 8.]])

In [38]:
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [39]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [40]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [41]:
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [42]:
print(x*y)

[[ 5. 12.]
 [21. 32.]]


In [43]:
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]


In [44]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [45]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [46]:
np.sum(x)

np.float64(10.0)

In [47]:
print(np.sum(x))

10.0


In [49]:
print(np.sum(x,axis=1))

[3. 7.]


In [50]:
print(np.sum(x,axis=0))

[4. 6.]


In [51]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [52]:
np.random.rand(5,5)

array([[0.84302559, 0.83752537, 0.06454319, 0.74827093, 0.4626567 ],
       [0.70567304, 0.94269034, 0.49294407, 0.64581022, 0.40489475],
       [0.65329975, 0.90080431, 0.14870235, 0.26904451, 0.47068172],
       [0.20750322, 0.37555516, 0.05846634, 0.53398681, 0.00785607],
       [0.56305422, 0.51959329, 0.03115992, 0.25784102, 0.02626173]])

In [53]:
np.random.randn(5)  #normal distributn of n numbers

array([-1.11492186,  1.1333171 , -2.33929423, -1.87908162,  1.16962299])

In [54]:
np.random.randint(1,100,10)

array([75, 45, 62, 49, 67, 92, 69,  5, 84,  5], dtype=int32)

In [55]:
A=np.matrix([[1,2,3,33],
            [4,5,6,66],
            [7,8,9,99]])
np.argmax(A)  #11,which is the position of 99

np.int64(11)

In [ ]:
np.argmax(A[:,:]) #11,which is the position of 99

np.int64(11)

In [ ]:
np.argmax(A[:1])    #3, which is the position of 33

np.int64(3)

In [ ]:
np.argmax(A[:,2])  #2,which is the position of 9

np.int64(2)